### PR TITLE
Run autoconf before building the extension. #40

### PR DESCRIPTION
**Pull request by gpshead**
Hopefully this addresses #40 and similar build failure issues on non-Linux non-macOS POSIX systems.

### CODE REVIEW

**Comment by dimpase** [comment]
On FreeBSD I see
```
_posixsubprocess.c:360:34: warning: implicit declaration of function 'dirfd' is invalid in C99 [-Wimplicit-function-declaration]                                                                            
            int fd_used_by_opendir = dirfd(proc_fd_dir);                                             
```
Missing check for including `dirent.h` ?

(In fact, the same warning with the current master branch, too)

**Comment by gpshead** [comment]
weird, AC_HEADER_DIRENT should've already been taking care of that.  I just added dirent.h explicitly to the list of checks now in addition to that but I doubt it'll make a difference given autoheader already listed it as something checked for in the .h.in file.  What does your generated _posixsubprocess_config.h say about HAVE_DIRENT_H after running configure?

**Comment by dimpase** [comment]
It looks as if dirent.h is included, but the corresponding `dirfd` declaration is not called, as it sits inside various ifdefs, see https://github.com/freebsd/freebsd/blob/0490c97003af3593d267cae1f89ebf3afe01af12/include/dirent.h#L108

**Comment by dimpase** [comment]
Well, if I comment out the [condition](https://github.com/freebsd/freebsd/blob/0490c97003af3593d267cae1f89ebf3afe01af12/include/dirent.h#L106) in dirent.h
```
#if __POSIX_VISIBLE >= 200809 || __XSI_VISIBLE >= 700
```
(and, naturally, the matching `#endif`) 
then the warning goes away. So it's definitely something with ` __POSIX_VISIBLE` not being set correctly.

**Comment by dimpase** [comment]
The warning does go away if I change the top of `_posixsubprocess.c` to look as follows:
```
#include "_posixsubprocess_config.h"
#include <sys/cdefs.h>
#define PY_SSIZE_T_CLEAN
#include "Python.h"
```

Thus `Python.h` is to blame for playing fast and loose with preprocessor variables.
E.g. it does
```
#define _POSIX_C_SOURCE 200112L
```

**Pull request merged**
